### ISSUE TITLE
Create paper template with key references in there

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/who3#12]

**Comment by mpadge** [comment]
@Robinlovelace I was thinking that maybe the calibration paper should live in it's own repo, so that:

1. Code and manuscript could live together in one clean repo to aid review process once it's submitted, and for reference following publication, as we did in the [geospatial stroke paper](https://github.com/richardbeare/GeospatialStroke).
2. We could may keep that private for the moment, at least until we decide where it will be submitted, because some journals may have issues with reviewing manuscripts that are publicly available?

**Comment by Robinlovelace** [comment]
I vote open to support open science, my most recent submission was completely open and that seems fine, allowing people to access and benefit from it earlier, and encouraging publishers to be permissive: https://osf.io/mpn3d/

Let me know when you'd like feedback on the draft - looks like you've got a good start going.

**Comment by Robinlovelace** [comment]
Closing as it seems the template is there. Great work @mpadge. How did you get on with the routing on RStudio Server Pro?

**Comment by mpadge** [comment]
Still trying to get an efficient way to calculate centrality ... not quite there yet

**Comment by Robinlovelace** [comment]
Cheers for the update. Can always revert back to igraph if needs be...
